all:
	gcc -o make-include-array make-include-array.c
	./make-include-array ../git-sysconfig ../git-sysconfig.h
	./make-include-array ../git-init-script ../git-init-script.h
	gcc -o test test.c
	./test
